# Generated by Django 5.2 on 2025-04-19 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_remove_sellrequest_bike_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiclePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Payment Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("delivery_address", models.TextField()),
                ("contact_number", models.CharField(max_length=15)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="emi_available",
            field=models.BooleanField(
                default=True, help_text="Whether EMI is available for this vehicle"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="emi_months",
            field=models.JSONField(
                default=list, help_text="Available EMI tenures in months"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="features",
            field=models.JSONField(default=list, help_text="List of vehicle features"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="highlights",
            field=models.JSONField(
                default=list, help_text="Key highlights of the vehicle"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="images",
            field=models.JSONField(
                default=dict,
                help_text='Format: {"thumbnail": "url", "main": "url", "gallery": ["url1", "url2"]}',
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Selling price of the vehicle",
                max_digits=10,
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["price"], name="marketplace_price_10cd5f_idx"),
        ),
        migrations.AddField(
            model_name="vehiclepurchase",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicle_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehiclepurchase",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="marketplace.vehicle",
            ),
        ),
    ]
