# Generated by Django 5.2 on 2025-04-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_emailverificationtoken_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("profile_photo", models.ImageField(upload_to="profiles/")),
                ("vehicle_name", models.CharField(max_length=255)),
                ("vehicle_type", models.CharField(max_length=255)),
                ("manufacturer", models.CharField(max_length=255)),
            ],
        ),
    ]
